package io.github.lucf15.tiffrenderer

import java.nio.file.Files
import java.util.Base64
import kotlin.test.Test
import kotlin.test.assertEquals

class TiffRendererJvmTest {
    @Test
    fun rendersRealFixtureWithExpectedColor() {
        val bytes = Base64.getDecoder().decode(SINGLE_PAGE_RGB_BASE64)
        val tempFile = Files.createTempFile("tiffrenderer_jvm_test", ".tif")
        Files.write(tempFile, bytes)

        try {
            TiffRenderer(TiffSource.fromFile(tempFile.toFile())).use { renderer ->
                assertEquals(1, renderer.pageCount)
                val page = renderer.openPage(0)
                assertEquals(32, page.width)
                assertEquals(24, page.height)

                val bitmap = createTiffBitmap(page.width, page.height)
                page.render(bitmap, renderMode = TiffRenderMode.FOR_DISPLAY)
                val pixel = bitmap.toIntArray()[0]

                assertEquals(128, pixel and 0xFF, "red")
                assertEquals(64, (pixel shr 8) and 0xFF, "green")
                assertEquals(200, (pixel shr 16) and 0xFF, "blue")
                assertEquals(255, (pixel shr 24) and 0xFF, "alpha")

                page.close()
            }
        } finally {
            Files.deleteIfExists(tempFile)
        }
    }
}

// Same fixture as lib/core/src/androidDeviceTest's single_page_rgb.tif: a flat-color 32x24 RGB
// page, rgb(128,64,200).
private const val SINGLE_PAGE_RGB_BASE64 =
    "SUkqAAgAAAAJAAABAwABAAAAIAAAAAEBAwABAAAAGAAAAAIBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAgAAABEBBAABAAAAegAAABUBAwABAAAAAwAAABYBAwABAAAAGAAAABcBBAABAAAAAAkAAAAAAACAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMiAQMg="
