/*
 * jconfig.h: hand-written for the vendored IJG libjpeg (third_party/libjpeg), since IJG doesn't
 * ship one (it's normally generated by ./configure). Values below are IJG's own "generic Unix"
 * jconfig.txt template unmodified; the JPEG_CJPEG_DJPEG block is omitted since this build never
 * compiles the standalone cjpeg/djpeg/jpegtran tools it applies to.
 */

#define HAVE_PROTOTYPES
#define HAVE_UNSIGNED_CHAR
#define HAVE_UNSIGNED_SHORT
/* #define void char */
/* #define const */
#undef CHAR_IS_UNSIGNED
#define HAVE_STDDEF_H
#define HAVE_STDLIB_H
#undef NEED_BSD_STRINGS
#undef NEED_SYS_TYPES_H
#undef NEED_FAR_POINTERS
#undef NEED_SHORT_EXTERNAL_NAMES
#undef INCOMPLETE_TYPES_BROKEN

#ifdef JPEG_INTERNALS
#undef RIGHT_SHIFT_IS_UNSIGNED
#endif

#ifdef _WIN32
/* Defining boolean here (jpeglib.h #includes this file) guarantees libjpeg and any external
 * caller (e.g. libtiff's tif_jpeg.c) agree on its size, instead of each picking up whatever
 * windows.h/rpcndr.h defines transitively, which previously caused a real size mismatch. */
#define HAVE_BOOLEAN
typedef unsigned char boolean;
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif
#endif
