/*
 * jconfig.h: hand-written configuration for the vendored IJG libjpeg
 * (third_party/libjpeg, github.com/libjpeg-turbo/ijg tag jpeg-10). Deliberately not part of that
 * submodule: jconfig.h is not shipped in the IJG distribution at all (see its own jconfig.txt),
 * normally generated by ./configure on a plain Unix build. Values below are IJG's own documented
 * "generic Unix" jconfig.txt template unmodified: every #define is unconditionally true for a
 * modern Clang/NDK target, every #undef is explicitly documented by IJG as the safe default. The
 * #ifdef JPEG_CJPEG_DJPEG block from the template is omitted entirely: those options only affect
 * the standalone cjpeg/djpeg/jpegtran command-line tools, which this build never compiles.
 */

#define HAVE_PROTOTYPES
#define HAVE_UNSIGNED_CHAR
#define HAVE_UNSIGNED_SHORT
/* #define void char */
/* #define const */
#undef CHAR_IS_UNSIGNED
#define HAVE_STDDEF_H
#define HAVE_STDLIB_H
#undef NEED_BSD_STRINGS
#undef NEED_SYS_TYPES_H
#undef NEED_FAR_POINTERS
#undef NEED_SHORT_EXTERNAL_NAMES
#undef INCOMPLETE_TYPES_BROKEN

#ifdef JPEG_INTERNALS
#undef RIGHT_SHIFT_IS_UNSIGNED
#endif

#ifdef _WIN32
/* Every translation unit that includes jpeglib.h picks this file up (jpeglib.h #includes
 * "jconfig.h" directly), so defining boolean here once is what actually guarantees libjpeg's own
 * compiled objects and any external caller (e.g. libtiff's tif_jpeg.c) agree on its size --
 * leaving it to whichever windows.h/rpcndr.h a given caller happens to transitively pull in is
 * what previously produced a real "library thinks size is 664, caller expects 632" mismatch. */
#define HAVE_BOOLEAN
typedef unsigned char boolean;
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif
#endif
