name: Check for libwebp updates

on:
  schedule:
    - cron: "0 6 * * 2"
  workflow_dispatch:

concurrency:
  group: libwebp-update-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-check:
    uses: ./.github/workflows/native-lib-update-check.yml
    with:
      library_name: libwebp
      repo_url: https://github.com/webmproject/libwebp
    secrets: inherit
